spring:
  data:
    mongodb:
      uri: mongodb://mongos:27017/itemsdb
    redis:
      cluster:
        nodes:
          - redis1:6379
          - redis2:6379
          - redis3:6379
server:
  port: 8080
external:
  service:
    url: http://localhost:8081
